c_stdlib_version:  # [linux64]
  - '2.17'         # [linux64]
rust_arch:
  - x86_64-unknown-linux-gnu    # [linux64]
  - aarch64-unknown-linux-gnu   # [aarch64]
  - powerpc64le-unknown-linux-gnu       # [ppc64le]
  - s390x-unknown-linux-gnu     # [s390x]
  - x86_64-pc-windows-msvc      # [win64]
  - x86_64-apple-darwin         # [osx and x86_64]
  - aarch64-apple-darwin        # [osx and arm64]
